/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        brandDark: "#0B0B0C",
      },
      fontFamily: {
        axiformaBlack: ["axiforma-black", "sans-serif"],
        axiformaBlack: ["axiforma-boldblackslant", "sans-serif"],
        axiformaBlack: ["axiforma-bolditalic", "sans-serif"],
        axiformaBlackItalic: ["axiforma-blackitalic", "sans-serif"],
        axiformaBold: ["axiforma-bold", "sans-serif"],
        axiformaBoldItalic: ["axiforma-bolditalic", "sans-serif"],
        axiformaBook: ["axiforma-book", "sans-serif"],
        axiformaBookItalic: ["axiforma-booitalic", "sans-serif"],
        axiformaExtraBold: ["axiforma-extrabold", "sans-serif"],
        axiformaExtraBoldItalic: ["axiforma-extrabolditalic", "sans-serif"],
        axiformaHeavy: ["axiforma-heavy", "sans-serif"],
        axiformaHeavyItalic: ["axiforma-heavyitalic", "sans-serif"],
        axiformaItalic: ["axiforma-italic", "sans-serif"],
        axiformaLight: ["axiforma-light", "sans-serif"],
        axiformaLightItalic: ["axiforma-lightitalic", "sans-serif"],
        axiformaMedium: ["axiforma-medium", "sans-serif"],
        axiformaMediumItalic: ["axiforma-mediumitalic", "sans-serif"],
        axiformaRegular: ["axiforma-regular", "sans-serif"],
        axiformaSemiBold: ["axiforma-semibold", "sans-serif"],
        axiformaSemiBoldItalic: ["axiforma-semibolditalic", "sans-serif"],
        axiformaThin: ["axiforma-thin", "sans-serif"],
        axiformaThinItalic: ["axiforma-thinitalic", "sans-serif"],
        soraBold: ["sora-bold", "sans-serif"],
        soraExtraBold: ["sora-extrabold", "sans-serif"],
        soraExtraLight: ["sora-extralight", "sans-serif"],
        soraLight: ["sora-light", "sans-serif"],
        soraMedium: ["sora-medium", "sans-serif"],
        soraRegular: ["sora-regular", "sans-serif"],
        soraSemiBold: ["sora-semibold", "sans-serif"],
        soraThin: ["sora-thin", "sans-serif"],
      },
      fontSize: {},
    },
  },
  plugins: [],
};
